#pragma once
#include<iostream>
#include<fstream>
#include<sstream>
#include<iomanip>
#include<numbers>
#include<vector>
#include<random>
#include<string>
#include<xstring>
#include<deque>
#include<queue>
#include<map>
#include<stdlib.h>
#include<stdio.h>
#include<conio.h>
#include<errno.h>
#include<algorithm>
#include<signal.h>
#include<limits.h>
#include<locale.h>
#ifdef _WIN32
#ifndef _WINDOWS_
#include<Windows.h>
#include<WindowsX.h>
#endif
#include<TlHelp32.h>
#include<ShObjIdl.h>
#include<winsvc.h>
#endif
#include<tchar.h>
#include<ctime>
#include<typeinfo>
#include<assert.h>
#include<source_location>
#include<thread>
#include<version>
#include<chrono>
#include<mutex>
#include<span>
#include<any>
